name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sed '57 s/ansible-playbook/ansible/g' Dockerfile
        cat Dockerfile
        docker build . --file Dockerfile --tag ansible:$(date +%s)
        docker tag ansible docker.pkg.github.com/netfirms/ansible_container/ansible:$(date +%s)
        docker push docker.pkg.github.com/netfirms/ansible_container/ansible:$(date +%s)
