name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sed -i '/["ansible-playbook"]/c\["ansible"]' Dockerfile
        cat Dockerfile
        docker build . --file Dockerfile --tag ansible:$(date +%s)
