name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ansible-playbook:$(date +%s)
        docker tag ansible-playbook docker.pkg.github.com/netfirms/ansible_container/ansible-playbook:$(date +%s)
        docker push docker.pkg.github.com/netfirms/ansible_container/ansible-playbook
